"""Knowledge Base feature package — RAG corpus + retrieval.

Lives in its own top-level backend package (not under `persistence/`) because
it owns its own database, its own SQLAlchemy Base, and its own Alembic
migration chain. Co-locating it with the main app's persistence layer would
risk cross-contamination during autogenerated migrations.
"""
