"""Add search_aliases to kb_documents.

User-editable comma-separated aliases prepended to chunk embeddings, so
queries phrased in customer terms can still hit chunks whose body uses
manufacturer SKUs.

Idempotent — same defensive pattern as the main DB's 0012 migration: if
the column already exists (e.g. autogenerated by create_all on a fresh
boot), we no-op and just stamp the revision.

Revision ID: kb_0002
Revises: kb_0001
Create Date: 2026-05-08
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "kb_0002"
down_revision: Union[str, None] = "kb_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(c["name"] == column for c in inspector.get_columns(table))


def upgrade() -> None:
    if _column_exists("kb_documents", "search_aliases"):
        return
    op.add_column(
        "kb_documents",
        sa.Column(
            "search_aliases",
            sa.Text(),
            nullable=False,
            server_default="",
        ),
    )


def downgrade() -> None:
    if not _column_exists("kb_documents", "search_aliases"):
        return
    op.drop_column("kb_documents", "search_aliases")
